# Generated by Django 4.1.6 on 2023-02-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='gerente_desc',
            field=models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='forma_pgto',
            field=models.CharField(choices=[('D', 'Dinheiro'), ('P', 'PIX'), ('CD', 'Cartao Débito'), ('CC', 'Cartao Crédito')], default='D', max_length=2),
        ),
    ]
