# Generated by Django 4.1.6 on 2023-02-14 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0002_atendimento_gerente_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='valor_pago',
        ),
    ]
