# Generated by Django 4.1.6 on 2023-02-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0003_remove_atendimento_valor_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='situacao',
            field=models.CharField(choices=[('P', 'PENDENTE'), ('R', 'REALIZADO'), ('C', 'CANCELADO')], default='P', max_length=1),
        ),
    ]
