# Generated by Django 4.1.6 on 2023-02-15 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atendimentos', '0004_atendimento_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='atendente',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Atendente'}, on_delete=django.db.models.deletion.CASCADE, related_name='Atendente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='helper',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Helper'}, on_delete=django.db.models.deletion.CASCADE, related_name='Helper', to=settings.AUTH_USER_MODEL),
        ),
    ]
