# Generated by Django 4.1.6 on 2023-02-15 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0008_alter_atendimento_atendente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='valor',
        ),
    ]
