# Generated by Django 4.1.6 on 2023-02-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0009_remove_atendimento_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
