# Generated by Django 4.1.6 on 2023-02-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0011_rename_forma_pgto_atendimento_formapgto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='data_atendimento',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='gerente_desc',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='situacao',
            field=models.CharField(choices=[('P', 'Pendente'), ('R', 'Realizado'), ('C', 'Cancelado')], default='P', max_length=1),
        ),
    ]
