# Generated by Django 4.1.6 on 2023-02-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0015_alter_atendimento_data_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='data_atendimento',
            field=models.DateField(auto_now_add=True),
        ),
    ]
