# Generated by Django 4.1.6 on 2023-02-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LIMPEZA SIMPLES', 'Limpeza Simples'), ('LIMPEZA PROFUNDA', 'Limpeza Profunda')], max_length=255)),
            ],
        ),
    ]
