# Generated by Django 4.1.6 on 2023-02-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='tipo',
        ),
        migrations.AddField(
            model_name='servico',
            name='descricao',
            field=models.TextField(default='Descrição'),
        ),
        migrations.AddField(
            model_name='servico',
            name='nome',
            field=models.CharField(default='gerente', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servico',
            name='valor',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=7),
            preserve_default=False,
        ),
    ]
